@host = localhost
@port = 40000
@baseUrl = http://{{host}}:{{port}}/v1

### status
GET {{baseUrl}}/status HTTP/1.1

### stop
@taskId = {{$randomInt 100 999}}
POST {{baseUrl}}/stop/{{taskId}} HTTP/1.1
Content-Type: application/json

### testcases
GET {{baseUrl}}/testcases HTTP/1.1
Content-Type: application/json

{
    "Tasks": "sdsd"
}
